//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class strona
    {
        public int Id { get; set; }
        public string numer { get; set; }
        public string il_obrazow { get; set; }
    
        public virtual ksiazka ksiazka { get; set; }
    }
}
